import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { FAQ, FinalCTA, SectionHeading, type Faq } from '@/modules/marketing/MarketingSections';
import PageMeta from '@/modules/marketing/PageMeta';

type Plan = { name: string; price: string; cadence?: string; detail: string; benefits: string[]; label: string; to: string; featured?: boolean };
const plans: Plan[] = [
  { name: 'Free', price: '$0', cadence: '/ month', detail: 'For individual educators exploring a focused planning workflow.', benefits: ['5 lesson plans per month', 'Basic PDF export', 'Two starter templates', 'Core planning workspace'], label: 'Start free', to: '/auth' },
  { name: 'Pro teacher', price: '$12', cadence: '/ month', detail: 'For educators building a more complete, repeatable workflow.', benefits: ['More planning capacity', 'Lesson, quiz, and worksheet tools', 'PDF and DOCX export', 'Reusable document library'], label: 'Choose Pro', to: '/auth', featured: true },
  { name: 'Schools', price: 'Let’s talk', detail: 'For teams planning a considered rollout and shared practice.', benefits: ['Team onboarding', 'Shared planning approach', 'Rollout guidance', 'Responsible-use planning'], label: 'Plan a pilot', to: '/contact' },
];
const comparison = [
  ['Lesson planning', 'Included', 'Included', 'Included'], ['Quiz and worksheet tools', 'Limited', 'Included', 'Included'], ['PDF export', 'Included', 'Included', 'Included'], ['DOCX export', '—', 'Included', 'Included'], ['Team rollout guidance', '—', '—', 'Included'],
];
const faqs: Faq[] = [
  { question: 'Can I start without a credit card?', answer: 'The free workspace is designed for exploration without a credit card. Confirm the final billing flow before publishing paid-plan details.' },
  { question: 'Can I change plans later?', answer: 'Plan upgrades and billing changes should be managed through the account billing experience once it is connected to the production billing configuration.' },
  { question: 'What is included for schools?', answer: 'School plans focus on team onboarding, a shared planning approach, and a considered rollout. Contact the team to shape the scope around your organisation.' },
  { question: 'Is student data required?', answer: 'No. Lesson planning should use general classroom context. Do not enter student identifiers, sensitive personal data, or confidential records.' },
];

const PricingPage: React.FC = () => <div className="bg-background-light">
  <PageMeta title="Pricing" description="Explore free, Pro teacher, and school plans for the curriculamIQ workspace." />
  <section className="pricing-hero px-5 py-20 lg:px-12 lg:py-28"><motion.div className="mx-auto max-w-4xl text-center" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><span className="eyebrow">Straightforward plans</span><h1 className="mt-5 text-4xl font-extrabold font-display tracking-[-.05em] sm:text-6xl">Choose the planning pace that works for you.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Start with one lesson, then choose the capacity and support that fit your teaching practice.</p></motion.div></section>
  <section className="px-5 pb-24 lg:px-12"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{plans.map((plan, index) => <motion.article key={plan.name} className={`soft-card relative flex min-h-[470px] flex-col rounded-3xl p-7 ${plan.featured ? 'featured-plan ring-2 ring-primary' : ''}`} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .1 }}>{plan.featured && <span className="absolute -top-3 left-7 rounded-full bg-primary px-3 py-1 text-xs font-extrabold uppercase tracking-wider text-white">Most popular</span>}<p className="text-sm font-extrabold text-primary">curriculamIQ</p><h2 className="mt-3 text-2xl font-extrabold">{plan.name}</h2><p className="mt-4 text-4xl font-extrabold font-display">{plan.price}{plan.cadence && <span className="ml-1 text-base font-medium text-slate-500">{plan.cadence}</span>}</p><p className="mt-4 min-h-14 leading-6 text-slate-600">{plan.detail}</p><ul className="mt-7 space-y-3">{plan.benefits.map((benefit) => <li key={benefit} className="flex gap-2 text-sm font-bold text-slate-700"><span className="material-symbols-outlined text-lg text-primary">check_circle</span>{benefit}</li>)}</ul><Link to={plan.to} className={`material-button mt-auto ${plan.featured ? 'material-primary' : 'material-secondary'}`}>{plan.label}<span className="material-symbols-outlined text-base">arrow_forward</span></Link></motion.article>)}</div><p className="mx-auto mt-8 max-w-3xl text-center text-xs leading-5 text-slate-500">Plan availability, limits, pricing, taxes, and service terms must be confirmed against the production billing configuration before publication.</p></section>
  <section className="bg-white px-5 py-24 lg:px-12"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Compare plans" title="Find the right starting point." /><div className="mt-10 overflow-x-auto rounded-3xl border border-slate-200"><table className="w-full min-w-[700px] border-collapse bg-white text-left"><thead><tr className="bg-slate-50"><th className="p-5 text-sm text-slate-500">Capability</th>{plans.map((plan) => <th key={plan.name} className="p-5 text-sm font-extrabold">{plan.name}</th>)}</tr></thead><tbody>{comparison.map(([feature, ...values]) => <tr key={feature} className="border-t border-slate-200"><th className="p-5 text-sm font-bold">{feature}</th>{values.map((value, index) => <td key={`${feature}-${index}`} className={`p-5 text-sm ${value === '—' ? 'text-slate-400' : 'font-semibold text-slate-600'}`}>{value}</td>)}</tr>)}</tbody></table></div></div></section>
  <section className="section-tint px-5 py-24 lg:px-12"><div className="mx-auto max-w-4xl"><SectionHeading eyebrow="Pricing questions" title="A little more detail." align="center" /><FAQ items={faqs} /></div></section>
  <FinalCTA eyebrow="For school teams" title="Planning a wider rollout? Start with a focused pilot." copy="Shape an adoption path around your educators, policies, and real planning workflows." action="Talk about your school" to="/contact" secondary={{ label: 'Explore schools', to: '/schools' }} />
</div>;
export default PricingPage;
