import React, { useEffect, useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';

const navItems = [{ to: '/product', label: 'Product' }, { to: '/schools', label: 'Schools' }, { to: '/pricing', label: 'Pricing' }, { to: '/trust-ai', label: 'Trust & AI' }];
const navClass = ({ isActive }: { isActive: boolean }) => `rounded-xl px-3 py-2 text-sm font-bold transition ${isActive ? 'bg-brand-yellow text-primary' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950'}`;

const PublicLayout: React.FC = () => {
  const [menuOpen, setMenuOpen] = useState(false);
  const location = useLocation();
  useEffect(() => setMenuOpen(false), [location.pathname]);
  return <div className="app-surface flex min-h-screen w-full flex-col font-body text-slate-900">
    <header className="site-header sticky top-0 z-50 border-b backdrop-blur-xl"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-3.5 lg:px-12"><Link to="/" className="flex items-center gap-3" aria-label="curriculamIQ home"><span className="brand-mark flex size-10 items-center justify-center rounded-xl text-white"><span className="material-symbols-outlined text-xl">auto_stories</span></span><span className="text-base font-extrabold font-display tracking-tight sm:text-lg md:text-xl">curriculamIQ</span></Link>
      <nav className="desktop-nav items-center gap-1" aria-label="Main navigation">{navItems.map((item) => <NavLink key={item.to} to={item.to} className={navClass}>{item.label}</NavLink>)}</nav>
      <div className="flex items-center gap-2 sm:gap-3"><Link to="/auth" className="hidden rounded-lg px-3 py-2 text-sm font-bold text-slate-700 hover:text-primary md:inline-flex">Log in</Link><Link to="/auth" className="material-button material-primary hidden text-sm sm:inline-flex">Start free <span className="material-symbols-outlined text-base">arrow_forward</span></Link><button type="button" className="menu-button flex size-11 items-center justify-center rounded-xl border border-slate-200 bg-white text-brand-black lg:hidden" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen((open) => !open)}><span className="material-symbols-outlined">{menuOpen ? 'close' : 'menu'}</span></button></div></div>
      {menuOpen && <nav className="mobile-nav border-t border-slate-200 bg-white px-5 py-4 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-6xl gap-1">{navItems.map((item) => <NavLink key={item.to} to={item.to} className={navClass}>{item.label}</NavLink>)}<div className="mt-3 grid grid-cols-2 gap-2 border-t border-slate-100 pt-4"><Link to="/auth" className="material-button material-secondary">Log in</Link><Link to="/auth" className="material-button material-primary">Start free</Link></div></div></nav>}
    </header>
    <main className="flex-grow"><Outlet /></main>
    <footer className="border-t border-slate-200 bg-white px-5 pb-8 pt-14 lg:px-12"><div className="mx-auto max-w-6xl"><div className="grid gap-10 border-b border-slate-200 pb-12 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Link to="/" className="flex items-center gap-3"><span className="brand-mark flex size-9 items-center justify-center rounded-xl text-white"><span className="material-symbols-outlined text-lg">auto_stories</span></span><span className="font-extrabold font-display">curriculamIQ</span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-slate-500">A calmer AI workspace for creating thoughtful lesson plans and classroom materials.</p></div><div><p className="footer-title">Product</p><div className="footer-links"><Link to="/product">Overview</Link><Link to="/pricing">Pricing</Link><Link to="/auth">Log in</Link></div></div><div><p className="footer-title">For teams</p><div className="footer-links"><Link to="/schools">Schools</Link><Link to="/contact">Contact</Link><Link to="/trust-ai">Trust & AI</Link></div></div><div><p className="footer-title">Legal</p><div className="footer-links"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div></div><div className="flex flex-col gap-3 pt-7 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} curriculamIQ. Thoughtful tools for educators.</p><p>AI drafts. Teachers decide.</p></div></div></footer>
  </div>;
};
export default PublicLayout;