import React, { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import LessonPlanGenerator from '@/modules/generation/apps/LessonPlanGenerator'; import SyllabusGenerator from '@/modules/generation/apps/SyllabusGenerator'; import QuestionPaperGenerator from '@/modules/generation/apps/QuestionPaperGenerator'; import QuizGenerator from '@/modules/generation/apps/QuizGenerator'; import StudyNotesGenerator from '@/modules/generation/apps/StudyNotesGenerator'; import ConceptMapGenerator from '@/modules/generation/apps/ConceptMapGenerator'; import LessonSequenceGenerator from '@/modules/generation/apps/LessonSequenceGenerator';
import AIUseNotice from '@/shared/ui/AIUseNotice';
import { AppType } from '@/shared/types/document';
type GeneratorApp = AppType | 'lesson-sequence' | null;
const tools: [Exclude<GeneratorApp, null>, string, string, string][] = [['lesson-plan', 'auto_stories', 'Lesson plan', 'Objectives, activities, and assessment.'], ['syllabus', 'calendar_month', 'Syllabus', 'Course outline and weekly schedule.'], ['paper', 'description', 'Exam paper', 'Balanced questions with answer keys.'], ['quiz', 'check_circle', 'MCQ quiz', 'Quick formative checks.'], ['study-notes', 'menu_book', 'Study notes', 'Revision materials and summaries.'], ['concept-map', 'account_tree', 'Concept map', 'Visualise relationships between ideas.'], ['lesson-sequence', 'format_list_numbered', 'Lesson sequence', 'Build a series from a concept map.']];
const GeneratePlanPage: React.FC = () => {
  const location = useLocation(); const [activeApp, setActiveApp] = useState<GeneratorApp>(null); const [requestedApp, setRequestedApp] = useState<GeneratorApp>(null);
  useEffect(() => { const state = location.state as { initialApp?: GeneratorApp }; if (state?.initialApp) setActiveApp(state.initialApp); }, [location]);
  const back = () => setActiveApp(null); const chooseTool = (tool: Exclude<GeneratorApp, null>) => localStorage.getItem('ai-use-notice-v1') ? setActiveApp(tool) : setRequestedApp(tool); const acceptAIUse = () => { if (requestedApp) setActiveApp(requestedApp); setRequestedApp(null); };
  if (activeApp === 'lesson-plan') return <LessonPlanGenerator onBack={back} />; if (activeApp === 'syllabus') return <SyllabusGenerator onBack={back} />; if (activeApp === 'paper') return <QuestionPaperGenerator onBack={back} />; if (activeApp === 'quiz') return <QuizGenerator onBack={back} />; if (activeApp === 'study-notes') return <StudyNotesGenerator onBack={back} />; if (activeApp === 'concept-map') return <ConceptMapGenerator onBack={back} />; if (activeApp === 'lesson-sequence') return <LessonSequenceGenerator onBack={back} />;
  return <div className="mx-auto flex max-w-6xl flex-col"><div className="mb-7 max-w-2xl"><p className="dashboard-kicker">AI planning studio</p><h1 className="mt-1 text-3xl font-extrabold font-display tracking-tight text-slate-900 dark:text-white">What would you like to create?</h1><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Choose a starting point for useful, classroom-ready material.</p></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">{tools.map(([id, icon, title, description]) => <button key={id} onClick={() => chooseTool(id)} className="dashboard-tool group"><span className="dashboard-icon bg-brand-yellow transition group-hover:bg-primary group-hover:text-white"><span className="material-symbols-outlined">{icon}</span></span><h2>{title}</h2><p>{description}</p><span className="mt-auto flex items-center gap-1 pt-4 text-sm font-bold text-primary">Create <span className="material-symbols-outlined text-base">arrow_forward</span></span></button>)}</div><AIUseNotice isOpen={requestedApp !== null} onAccept={acceptAIUse} onClose={() => setRequestedApp(null)} /></div>;
};
export default GeneratePlanPage;
